name: deploy
on:
    workflow_dispatch:

jobs:
    deploy: 
        name: Deploy to VPS
        runs-on: ubuntu-22.04
        steps:
            - name: Deploy 
              uses: appleboy/ssh-action@v0.1.8
              with:
                host: 79.143.93.25
                port: 2222
                username: yeray
                key: ${{secrets.PRIVATE_KEY}}
                script: "cd /var/www/html/laravelvps; git pull origin main; npm run build"
            - name: Reload PHP-FPM
              run: sudo /usr/sbin/seervice php8.2-fpm reload